trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  major: '0'
  minor: '1'
  patch: '0'

steps:
- task: UseDotNet@2
  displayName: 'Install sdk version'
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: NuGetCommand@2
  inputs:
    command: pack
    packagesToPack: '**/SD-JWT.csproj'
    packDestination: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byPrereleaseNumber
    majorVersion: '$(major)'
    minorVersion: '$(minor)'
    patchVersion: '$(patch)'

- task: NuGetAuthenticate@1

- task: NuGetCommand@2
  inputs:
    command: push
    publishVstsFeed: 'OID4VC/lissi-oid4vc'