trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
      - task: UseDotNet@2
        displayName: 'Install sdk version'
        inputs:
          packageType: 'sdk'
          version: '6.x'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'restore'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          arguments: '--configuration $(buildConfiguration)'
        displayName: 'dotnet build $(buildConfiguration)'

      - task: PublishPipelineArtifact@0
        inputs:
          artifactName: "drop"
          targetPath: "$(Build.ArtifactStagingDirectory)"
