name: CI

on:
  push:
    branches:
      - setup-cicd-pipeline-nuget
  pull_request:
    branches:
      - setup-cicd-pipeline-nuget

jobs:
  build:

    env:
      MAJOR: 0
      MINOR: 1
      PATCH: 0
      APP_VERSION: $MAJOR.$MINOR.$PATCH
      BUILD_CONFIG: 'Release'
      SOLUTION: 'SD-JWT.sln'

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Build Version
        run: |
          Write-Host $Env:GITHUB_REF
        shell: pwsh

      - name: Display Variable
        run: |
          echo "Variable Value: $APP_VERSION"

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore dependencies
        run: nuget restore $SOLUTION

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.*

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$APP_VERSION --no-restore

      - name: Run tests
        run: dotnet test /p:Configuration=$env:BUILD_CONFIG --no-restore --no-build --verbosity normal

#      - name: Publish
#        if: startsWith(github.ref, 'refs/heads/release')
#        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}