name: CI

on:
  push:
    branches:
      - setup-cicd-pipeline-nuget
  pull_request:
    branches:
      - setup-cicd-pipeline-nuget

env:
  APP_VERSION: 0.1.0
  BUILD_CONFIG: 'Release'
  SOLUTION: 'SD-JWT.sln'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Get Build Version
        run: |
          Write-Host $Env:GITHUB_REF
        shell: pwsh

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore dependencies
        run: nuget restore $SOLUTION

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 3.1.*

      - name: Build
        run: dotnet build $SOLUTION --configuration $BUILD_CONFIG -p:Version=$APP_VERSION --no-restore

      - name: Run tests
        run: dotnet test /p:Configuration=$BUILD_CONFIG --no-restore --no-build --verbosity normal

#      - name: Publish
#        if: startsWith(github.ref, 'refs/heads/release')
#        run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}}